name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: eclipse-app
          path: ./deploy

      - name: Restart application
        run: |
          echo "Stopping old app if running..."
          pkill -f "dotnet Eclipse.dll" || echo "No process found"

          echo "Starting new app..."
          cd ./deploy
          nohup dotnet Eclipse.dll > app.log 2>&1 &
          echo "App started. Logs: ./deploy/app.log"
