name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: eclipse-app
          path: /home/tedecti/eclipse-app

      - name: Create systemd service
        run: |
          SERVICE_FILE=/etc/systemd/system/eclipse.service
          sudo bash -c "cat > $SERVICE_FILE" <<EOL
          [Unit]
          Description=Eclipse App
          After=network.target

          [Service]
          ExecStart=/usr/bin/dotnet /home/tedecti/eclipse-app/Eclipse.dll
          WorkingDirectory=/home/tedecti/eclipse-app
          Restart=always
          User=tedecti

          [Install]
          WantedBy=multi-user.target
          EOL

          sudo systemctl daemon-reload
          sudo systemctl enable eclipse
          sudo systemctl restart eclipse

      - name: Check app health
        run: |
          sleep 5
          curl -I http://localhost:8080 || echo "App not responding"
