name: Local CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted   # <--- ключевое!
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          dotnet publish Eclipse/Eclipse.csproj -c Release -o ./publish

      - name: Restart app
        run: |
          pkill -f "dotnet Eclipse.dll" || true
          nohup dotnet ./publish/Eclipse.dll > app.log 2>&1 &
