name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIGURATION: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration $BUILD_CONFIGURATION --no-restore

      - name: Publish
        run: dotnet publish ./Eclipse/Eclipse.csproj -c $BUILD_CONFIGURATION -o ./publish /p:UseAppHost=false
