name: CI-CD

on:
  pull_request:
    branches:
      - develop
  push: 
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Eclipse/Eclipse.csproj

      - name: Install libssl1.1 from archive
        run: |
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
          && sudo dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb

      - name: Publish project
        run: |
          dotnet publish ./Eclipse/Eclipse.csproj \
            -c Release \
            -o ./publish \
            /p:UseAppHost=false

      - uses: actions/upload-artifact@v4
        with:
          name: eclipse-app
          path: ./publish

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: eclipse-app
          path: ./deploy

      - name: Deploy and restart with Supervisor
        run: |
          echo "Stopping ASP.NET Core app..."
          sudo supervisorctl stop aspnet || true

          echo "Deploying new files..."
          sudo rm -rf /cloudclusters/default_site/bin/release/net5.0/*
          sudo cp -r ./deploy/* /cloudclusters/default_site/bin/release/net5.0/
          sudo chown -R $USER:$USER /cloudclusters/default_site/bin/release/net5.0

          echo "Starting ASP.NET Core app..."
          sudo supervisorctl start aspnet

          echo "Checking status..."
          sudo supervisorctl status aspnet
