name: CI-CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Eclipse/Eclipse.csproj

      - name: Publish
        run: dotnet publish ./Eclipse/Eclipse.csproj -c Release -o ./publish /p:UseAppHost=false

      - uses: actions/upload-artifact@v4
        with:
          name: eclipse-app
          path: ./publish

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: eclipse-app
          path: ./deploy

      - name: Deploy and restart service
        run: |
          echo "Stopping service..."
          sudo systemctl stop eclipse.service

          echo "Deploying new files..."
          sudo rm -rf /home/tedecti/eclipse/*
          sudo cp -r ./deploy/* /home/tedecti/eclipse/
          sudo chown -R tedecti:tedecti /home/tedecti/eclipse

          echo "Starting service..."
          sudo systemctl start eclipse.service

          echo "Service status:"
          sudo systemctl status eclipse.service --no-pager
